spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:postgresql://localhost:5432/notification_db
    username: smartstudy
    password: smartstudy
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  rabbitmq:
    host: localhost
    port: 5672
    username: smartstudy
    password: smartstudy

server:
  port: 8084

management:
  endpoints:
    web:
      exposure:
        include: health,info
