spring:
  application:
    name: identity-service
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${IDENTITY_DB_NAME:identity_db}
    username: ${POSTGRES_USER:smartstudy}
    password: ${POSTGRES_PASSWORD:smartstudy}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    open-in-view: false

server:
  port: ${PORT:8081}
  address: 0.0.0.0

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
    register-with-eureka: ${EUREKA_REGISTER:true}
    fetch-registry: ${EUREKA_FETCH:true}
  instance:
    prefer-ip-address: false
    hostname: ${EUREKA_INSTANCE_HOSTNAME:identity-service.railway.internal}


management:
  endpoints:
    web:
      exposure:
        include: health,info

firebase:
  credentials-path: ${FIREBASE_CREDENTIALS:/app/credentials/firebase-admin.json}