spring:
  application:
    name: identity-service
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
  jpa:
    open-in-view: false

server:
  port: ${PORT:8081}
  address: 0.0.0.0

eureka:
  client:
    register-with-eureka: ${EUREKA_REGISTER:true}
    fetch-registry: ${EUREKA_FETCH:true}

management:
  endpoints:
    web:
      exposure:
        include: health,info

firebase:
  credentials-path: ${FIREBASE_CREDENTIALS:}
  credentials-json: ${FIREBASE_CREDENTIALS_JSON:}
