server:
  port: ${PORT:8080}
  address: 0.0.0.0

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.web.reactive.DispatcherHandler: TRACE
    reactor.netty.http.server.AccessLog: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info, gateway
  endpoint:
    health:
      show-details: never

spring:
  application:
    name: api-gateway
  codec:
    max-in-memory-size: 25MB
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      routes:
        - id: identity-service
          uri: lb://IDENTITY-SERVICE
          predicates:
            - name: Path
              args:
                patterns:
                  - /api/v1/auth/**
                  - /api/v1/users/**
          filters:
            - StripPrefix=2
            - name: CircuitBreaker
              args:
                name: identityCircuitBreaker
                fallbackUri: forward:/fallback/identity

        - id: planning-service
          uri: lb://PLANNING-SERVICE
          predicates:
            - name: Path
              args:
                patterns:
                  - /api/v1/tasks/**
                  - /api/v1/courses/**
                  - /api/v1/materials/**
                  - /api/v1/upload/**
                  - /api/v1/roadmap/**
                  - /api/v1/sessions/**
                  - /api/v1/auth/calendar/**
                  - /api/v1/home/**
          filters:
            - StripPrefix=2
            - name: RequestSize
              args:
                maxSize: 25MB
            - name: CircuitBreaker
              args:
                name: planningCircuitBreaker
                fallbackUri: forward:/fallback/planning
  config:
    import: optional:configserver:${CONFIG_SERVER_URI:http://localhost:8888}

firebase:
  credentials-path: ${FIREBASE_CREDENTIALS:}
  credentials-json: ${FIREBASE_CREDENTIALS_JSON:}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: false
    hostname: ${EUREKA_INSTANCE_HOSTNAME:api-gateway.railway.internal}
